---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - name: Install nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Configure firewall
      ansible.posix.firewalld:
       service: http
       permanent: true
       state: enabled

    - name: Start and enable nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
        
        
        
